#!/usr/bin/env python
'''
Main del traductor del Lenguaje Trinity
Creado:8/10/14
Ult.Mod:8/10/14
Autores:
	Carlo Polisano S. 0910672
	Alejandro Guevara 0910971
'''
import sys
from lexer import PLYCompatLexer
from parser import Sintaxer

if __name__ == '__main__':
	
	archivo = open(sys.argv[1], 'r')

	buff = archivo.read() # Todo el archivo en un solo string
	copia = buff

	# Cerrando Archivo
	archivo.close()
	
	lx=PLYCompatLexer(buff)
	
	#lista = [
		#('t_SUMA'),
		#('t_NUMERO'),
		#('t_IGUAL')
		#]
	lista=[
	('READ'),
	('PROGRAM'),
	('USE'),
	('BEGIN'),
	('IN'),
	('END'),
	('FUNCTION'),
	('RETURN'),
	('IF'),
	('THEN'),
	('FOR'),
	('ELSE'),
	('DO'),
	('WHILE'),
	('NUMBER'),
	('BOOLEAN'),
	('TRUE'),
	('FALSE'),
	('MATRIX'),
	('ROW'),
	('COL'),
	('PRINT'),
	('SET'),
	('NOT'),
	('MMOD'),
	('MDIV'),
	('MSUMA'),
	('MMENOS'),
	('MAST'),
	('MSLASH'),
	('MPORCENTAJE'),
	('PUNTOYCOMA'),
	('DOSPUNTOS'),
	('IGUAL2'),
	('DISTINTO'),
	('MAYORIGUAL'),
	('MENORIGUAL'),
	('MAYORQUE'),
	('MENORQUE'),
	('IGUAL'),
	('COMA'),
	('DIV'),
	('MOD'),
	('SUMA'),
	('MENOS'),
	('AST'),
	('SLASH'),
	('AND'),
	('OR'),
	('PORCENTAJE'),
	('PARENTESISABRE'),
	('PARENTESISCIERRA'),
	('CORCHETEABRE'),
	('CORCHETECIERRA'),
	('LLAVESABRE'),
	('LLAVESCIERRA'),
	('STRING'),
	('COMILLASIMPLE'),
	('NUMERO'),
	('ID')]
	x=Sintaxer(lx,lista, copia)
	exit(x)
	